steps:
  # Paso 1: Construir la imagen Docker
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/horario-ceprunsa-repo/horario-ceprunsa:latest"
      - "."

  # Paso 2: Subir la imagen a Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/horario-ceprunsa-repo/horario-ceprunsa:latest"

  # Paso 3: Desplegar en Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "horario-ceprunsa"
      - "--image"
      - "us-west1-docker.pkg.dev/$PROJECT_ID/horario-ceprunsa-repo/horario-ceprunsa:latest"
      - "--platform=managed"
      - "--region=us-west1"
      - "--allow-unauthenticated"

images:
  - "us-west1-docker.pkg.dev/$PROJECT_ID/horario-ceprunsa-repo/horario-ceprunsa:latest"

timeout: 1200s

