steps:
  # Autenticación con Secret Manager y exportación a .env
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=DATABASE_URL > .env
        gcloud secrets versions access latest --secret=DB_HOST >> .env
        gcloud secrets versions access latest --secret=DB_PORT >> .env
        gcloud secrets versions access latest --secret=DB_USER >> .env
        gcloud secrets versions access latest --secret=DB_DATABASE >> .env
        gcloud secrets versions access latest --secret=DB_PASSWORD >> .env
        gcloud secrets versions access latest --secret=GOOGLE_CLIENT_ID >> .env
        gcloud secrets versions access latest --secret=GOOGLE_CLIENT_SECRET >> .env
        gcloud secrets versions access latest --secret=GOOGLE_REDIRECT_URI >> .env
        gcloud secrets versions access latest --secret=JWT_SECRET >> .env
        gcloud secrets versions access latest --secret=JWT_EXPIRES_IN >> .env
        gcloud secrets versions access latest --secret=REDIRECT_FRONT >> .env
        cat .env

  # Instalación de dependencias con npm ci
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  # Asegura que Prisma CLI está instalado
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--save-dev', '@prisma/cli']

  # Generación de cliente Prisma
  - name: 'gcr.io/cloud-builders/npm'
    args: ['exec', 'prisma', 'generate']

  # Compilación del código NestJS
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Construcción de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back', '.']

  # Push de la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back']

  # Despliegue en Cloud Run con variables de entorno desde Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'horarios-cepre-back'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,DB_HOST=DB_HOST:latest,DB_PORT=DB_PORT:latest,DB_USER=DB_USER:latest,DB_DATABASE=DB_DATABASE:latest,DB_PASSWORD=DB_PASSWORD:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REDIRECT_URI=GOOGLE_REDIRECT_URI:latest,JWT_SECRET=JWT_SECRET:latest,JWT_EXPIRES_IN=JWT_EXPIRES_IN:latest,REDIRECT_FRONT=REDIRECT_FRONT:latest'

options:
  logging: CLOUD_LOGGING_ONLY
