steps:
  # Authenticate and retrieve secrets from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Create .env file securely
        echo "Retrieving secrets from Secret Manager..."
        gcloud secrets versions access latest --secret=DATABASE_URL > .env
        gcloud secrets versions access latest --secret=DB_HOST >> .env
        gcloud secrets versions access latest --secret=DB_PORT >> .env
        gcloud secrets versions access latest --secret=DB_USER >> .env
        gcloud secrets versions access latest --secret=DB_DATABASE >> .env
        gcloud secrets versions access latest --secret=DB_PASSWORD >> .env
        gcloud secrets versions access latest --secret=GOOGLE_CLIENT_ID >> .env
        gcloud secrets versions access latest --secret=GOOGLE_CLIENT_SECRET >> .env
        gcloud secrets versions access latest --secret=GOOGLE_REDIRECT_URI >> .env
        gcloud secrets versions access latest --secret=JWT_SECRET >> .env
        gcloud secrets versions access latest --secret=JWT_EXPIRES_IN >> .env
        gcloud secrets versions access latest --secret=REDIRECT_FRONT >> .env
        
        # Securely set file permissions
        chmod 600 .env
        echo "Secrets retrieved successfully."

  # Install dependencies
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['ci', '--prefer-offline', '--no-audit']

  # Generate Prisma client
  - name: 'node:22'
    entrypoint: 'npx'
    args: ['prisma', 'generate']

  # Run tests (optional, but recommended)
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'test']

  # Build the application
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build Docker image
  - name: 'docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back:$COMMIT_SHA', 
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back:latest', 
      '.'
    ]

  # Push Docker image to Artifact Registry
  - name: 'docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back', 
      '--all-tags'
    ]

  # Deploy to Cloud Run
  - name: 'gcloud'
    args: [
      'run', 'deploy', 'horarios-cepre-back',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-secrets', 
      'DATABASE_URL=DATABASE_URL:latest,DB_HOST=DB_HOST:latest,DB_PORT=DB_PORT:latest,DB_USER=DB_USER:latest,DB_DATABASE=DB_DATABASE:latest,DB_PASSWORD=DB_PASSWORD:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,GOOGLE_REDIRECT_URI=GOOGLE_REDIRECT_URI:latest,JWT_SECRET=JWT_SECRET:latest,JWT_EXPIRES_IN=JWT_EXPIRES_IN:latest,REDIRECT_FRONT=REDIRECT_FRONT:latest'
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back'

options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: ALLOW_LOOSE