steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-cepre-back/horarios-cepre-back'
      - '--build-arg=DATABASE_URL=$(DATABASE_URL)'
      - '--build-arg=DB_HOST=$(DB_HOST)'
      - '--build-arg=DB_PORT=$(DB_PORT)'
      - '--build-arg=DB_USER=$(DB_USER)'
      - '--build-arg=DB_DATABASE=$(DB_DATABASE)'
      - '--build-arg=DB_PASSWORD=$(DB_PASSWORD)'
      - '--build-arg=GOOGLE_CLIENT_ID=$(GOOGLE_CLIENT_ID)'
      - '--build-arg=GOOGLE_CLIENT_SECRET=$(GOOGLE_CLIENT_SECRET)'
      - '--build-arg=GOOGLE_REDIRECT_URI=$(GOOGLE_REDIRECT_URI)'
      - '--build-arg=JWT_SECRET=$(JWT_SECRET)'
      - '--build-arg=JWT_EXPIRES_IN=$(JWT_EXPIRES_IN)'
      - '--build-arg=REDIRECT_FRONT=$(REDIRECT_FRONT)'
      - '.'
    secretEnv:
      - DATABASE_URL
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_DATABASE
      - DB_PASSWORD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_REDIRECT_URI
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - REDIRECT_FRONT

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-cepre-back/horarios-cepre-back']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'horarios-cepre-back'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/horarios-cepre-back/horarios-cepre-back'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=DATABASE_URL=$(DATABASE_URL)'
      - '--set-env-vars=DB_HOST=$(DB_HOST)'
      - '--set-env-vars=DB_PORT=$(DB_PORT)'
      - '--set-env-vars=DB_USER=$(DB_USER)'
      - '--set-env-vars=DB_DATABASE=$(DB_DATABASE)'
      - '--set-env-vars=DB_PASSWORD=$(DB_PASSWORD)'
      - '--set-env-vars=GOOGLE_CLIENT_ID=$(GOOGLE_CLIENT_ID)'
      - '--set-env-vars=GOOGLE_CLIENT_SECRET=$(GOOGLE_CLIENT_SECRET)'
      - '--set-env-vars=GOOGLE_REDIRECT_URI=$(GOOGLE_REDIRECT_URI)'
      - '--set-env-vars=JWT_SECRET=$(JWT_SECRET)'
      - '--set-env-vars=JWT_EXPIRES_IN=$(JWT_EXPIRES_IN)'
      - '--set-env-vars=REDIRECT_FRONT=$(REDIRECT_FRONT)'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/DB_HOST/versions/latest
      env: 'DB_HOST'
    - versionName: projects/$PROJECT_ID/secrets/DB_PORT/versions/latest
      env: 'DB_PORT'
    - versionName: projects/$PROJECT_ID/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/$PROJECT_ID/secrets/DB_DATABASE/versions/latest
      env: 'DB_DATABASE'
    - versionName: projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: 'GOOGLE_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_SECRET/versions/latest
      env: 'GOOGLE_CLIENT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_REDIRECT_URI/versions/latest
      env: 'GOOGLE_REDIRECT_URI'
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/JWT_EXPIRES_IN/versions/latest
      env: 'JWT_EXPIRES_IN'
    - versionName: projects/$PROJECT_ID/secrets/REDIRECT_FRONT/versions/latest
      env: 'REDIRECT_FRONT'


images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/horarios-repo/horarios-cepre-back:$SHORT_SHA'


options:
  logging: CLOUD_LOGGING_ONLY

